version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: likelion-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: likelion-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8084:8080"
    env_file:
      - .env

volumes:
  db-data:
