spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

openai:
  enabled: ${OPENAI_ENABLED:true}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_BASE_URL:https://api.openai.com/v1/chat/completions}
  timeout-seconds: ${OPENAI_TIMEOUT_SECONDS:30}

logging:
  level:
    org.hibernate.SQL: INFO
    root: INFO

app:
  upload:
    dir: /var/data/uploads